# Generated by Django 4.2.11 on 2024-04-21 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingPlace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=255)),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_parking_space",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("license_plate", models.CharField(max_length=10)),
                (
                    "powertrain",
                    models.CharField(
                        choices=[("ICE", "Ice"), ("EV", "Ev")],
                        default="ICE",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("price_per_minute", models.FloatField(default=0.0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="AVAILABLE",
                        max_length=64,
                    ),
                ),
                ("accessible_parking", models.BooleanField(default=False)),
                ("ev_parking", models.BooleanField(default=False)),
                (
                    "parking_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_spaces",
                        to="parking_place.parkingplace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
