# Generated by Django 4.2.11 on 2024-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_place", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspace",
            name="price_per_minute",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
