# Generated by Django 4.2.11 on 2024-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="actual_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="surcharge_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
