# Generated by Django 4.2.11 on 2024-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_reservation_actual_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
