# Generated by Django 4.2.11 on 2024-04-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_reservation_confirmed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="actual_end",
            new_name="parking_end",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="confirmed",
        ),
        migrations.AddField(
            model_name="reservation",
            name="parking_start",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_status",
            field=models.CharField(
                choices=[("CONFIRMED", "Confirmed"), ("CANCELLED", "Cancelled")],
                default="CONFIRMED",
                max_length=16,
            ),
        ),
    ]
